server {
  listen 80;

  # Все запросы (включая главную страницу) отправляем на Django
  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://payment:8000;
  }

  # Админку тоже оставляем на Django
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://payment:8000;
  }

  # А вот статику (картинки, стили) Nginx заберет сам из папки
  location /static/ {
    alias /staticfiles/;
  }
}
