# Generated by Django 6.0 on 2025-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_prev', models.FloatField()),
                ('cold_curr', models.FloatField()),
                ('hot_prev', models.FloatField()),
                ('hot_curr', models.FloatField()),
                ('electricity', models.FloatField(default=0)),
                ('internet', models.FloatField(default=0)),
                ('cold_cost', models.FloatField()),
                ('hot_cost', models.FloatField()),
                ('sewage_cost', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
